//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by UETools-GUI.rc
//
#define APP_VERSION_MAJOR               5
#define APP_VERSION_MINOR               5
#define APP_VERSION_PATCH               2
#define APP_VERSION_BUILD               0

#define APP_VERSION_INTERNAL_HELPER(x) #x
#define APP_VERSION_INTERNAL_TOSTR(x) APP_VERSION_INTERNAL_HELPER(x)

#define APP_VERSION_STRING_FULL APP_VERSION_INTERNAL_TOSTR(APP_VERSION_MAJOR) "." APP_VERSION_INTERNAL_TOSTR(APP_VERSION_MINOR) "." APP_VERSION_INTERNAL_TOSTR(APP_VERSION_PATCH) "." APP_VERSION_INTERNAL_TOSTR(APP_VERSION_BUILD)
#define APP_VERSION_STRING_SHORT APP_VERSION_INTERNAL_TOSTR(APP_VERSION_MAJOR) "." APP_VERSION_INTERNAL_TOSTR(APP_VERSION_MINOR)

#define Actor_Green                     101
#define Actor_Red                       102

#define SIZE_BUFFER_POSITIONSENTRY      255
#define SIZE_BUFFER_SINGLEOBJECTPATH    2048
#define SIZE_BUFFER_SEARCHFILTER        2048
#define SIZE_BUFFER_CONSOLE             2048
#define SIZE_BUFFER_MULTIOBJECTPATH     16384

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        103
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
